async function testNotifications() {
  const baseUrl = 'http://localhost:5000/api';
  console.log('Testing Notifications API...');
  
  try {
    // 1. Get stats
    console.log('Testing GET /api/notifications/stats');
    const statsRes = await fetch(`${baseUrl}/notifications/stats?userId=1`);
    const stats = await statsRes.json();
    console.log('Stats:', stats);
    
    // 2. Get all
    console.log('Testing GET /api/notifications');
    const allRes = await fetch(`${baseUrl}/notifications?userId=1`);
    const all = await allRes.json();
    console.log('Total notifications:', all.length);
    
    // 3. Create one
    console.log('Testing POST /api/notifications');
    const newNotifRes = await fetch(`${baseUrl}/notifications`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userId: 1,
        type: 'test',
        title: 'Test Notification',
        message: 'This is a test notification generated by the verification script.',
        priority: 'medium'
      })
    });
    const newNotif = await newNotifRes.json();
    console.log('Created:', newNotif.id);
    
    // 4. Mark as read
    console.log(`Testing PATCH /api/notifications/${newNotif.id}/read`);
    const readRes = await fetch(`${baseUrl}/notifications/${newNotif.id}/read`, {
      method: 'PATCH'
    });
    const read = await readRes.json();
    console.log('Marked as read:', read.read);
    
    console.log('All tests passed!');
  } catch (error) {
    console.error('Test failed:', error.message);
  }
}

testNotifications();
